# set the name for the project
name: netsec_project

services:
  client:
    image: netsos/rhit-netsec:fw
    container_name: client
    hostname: client
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      subnet1:
        ipv4_address: 10.10.0.4
    extra_hosts:
      server: "10.10.1.5"
      honeypot: "10.10.2.20"
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      bash /volumes/configure_server.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      apt update &&
      apt install -y hydra &&
      ip route add 10.10.1.0/24 dev eth0 via 10.10.0.10 &&
      tail -f /dev/null
      "

  #
  # Firewall sits at the boundary
  #
  firewall:
    image: netsos/rhit-netsec:fw
    container_name: firewall
    hostname: firewall
    tty: true
    cap_add:
      - ALL
    volumes:
      - ./volumes/:/volumes
    sysctls:
      - net.ipv4.ip_forward=1
    extra_hosts:
      server: "10.10.1.5"
      honeypot: "10.10.2.20"
      client: "10.10.0.4"
    networks:
      subnet1:
        ipv4_address: 10.10.0.10
      subnet2:
        ipv4_address: 10.10.1.10
      subnet3:
        ipv4_address: 10.10.2.10
    command: >
      bash -c "
      groupadd netsec_group &&
      useradd -m -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      nft -f /volumes/firewall.nft &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      tail -f /dev/null
      "

  honeypot:
    # image: python:3.12
    container_name: honeypot
    hostname: honeypot
    build: ./honey
    tty: true
    cap_add:
      - ALL
    volumes:
      - ./honey/:/honey
    networks:
      subnet3:
        ipv4_address: 10.10.2.20
    # command: >
    #   bash -c "
    #   groupadd netsec_group &&
    #   useradd -m -g netsec_group -s /bin/bash netsec &&
    #   echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers "
    #   bash /volumes/check_config.sh &&
    #   nft -f /volumes/firewall.nft &&
    #   cp /volumes/vimrc /home/netsec/.vimrc &&
    #   tail -f /dev/null
    #   "

  server:
    image: netsos/rhit-netsec:fw
    container_name: server
    hostname: server
    tty: true
    working_dir: /volumes/
    cap_add:
      - ALL
    volumes:
      - ./volumes:/volumes
    networks:
      subnet2:
        ipv4_address: 10.10.1.5
    extra_hosts:
      client: "10.10.0.4"
    command: >
      bash -c "
      groupadd -g ${GID} netsec_group &&
      useradd -m -u ${UID} -g netsec_group -s /bin/bash netsec &&
      echo 'netsec ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      bash /volumes/check_config.sh &&
      bash /volumes/setup_telnetd.sh &&
      bash /volumes/configure_server.sh &&
      cp /volumes/vimrc /home/netsec/.vimrc &&
      ip route add 10.10.0.0/24 dev eth0 via 10.10.1.10 &&
      tail -f /dev/null
      "

networks:
  subnet1:
    name: subnet1
    ipam:
      config:
        - subnet: 10.10.0.0/24
  subnet2:
    name: subnet2
    ipam:
      config:
        - subnet: 10.10.1.0/24
  subnet3:
    name: subnet3
    ipam:
      config:
        - subnet: 10.10.2.0/24
